@api = http://localhost:3001/api/auth


### Login by username
POST {{api}}/login
Content-Type: application/json

{
    "username": "kriz",
    "password": "admin"
}

### Login by email
POST {{api}}/login
Content-Type: application/json

{
    "username": "jhon.doe@yopmail.com",
    "password": "admin"
}
