@api = http://localhost:3001/api/projects


### Get all projects
GET {{api}}/all

### Get  project by id
GET {{api}}/8ecb9752-75c1-4c37-a32d-9775becffa18

### Create project
POST {{api}}/create/userOwner/a71e0855-0284-4ea5-9bc9-19bb47eb9a8a
x_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQ1JFQVRPUiIsInN1YiI6ImE3MWUwODU1LTAyODQtNGVhNS05YmM5LTE5YmI0N2ViOWE4YSIsImlhdCI6MTY4OTgwNTA4NCwiZXhwIjoxNjg5ODA4Njg0fQ.c2Mnw9GyFSjHQut0_T-YTpb7O4ZABpWXDT_P9K6nGxs
Content-Type: application/json

{
    "name": "Test project 2",
    "description": "Testing projects resources"
}

### Update project
PUT {{api}}/edit/8ecb9752-75c1-4c37-a32d-9775becffa18
Content-Type: application/json

{
    "name": "Test project",
    "description": "Testing projects endpoints"
}

### Delete project
DELETE  {{api}}/delete/332f023a-0f5d-44fb-954b-9b8ea335d72b
