@api = http://localhost:3001/api/users


### Hello
GET {{api}}/say-hello

### Get all users
GET {{api}}/all
x_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQkFTSUMiLCJzdWIiOiJhYTI1NWExZC03OGUwLTQyYTMtOTUxZS0wNWRhZjMyMzEwMzAiLCJpYXQiOjE2ODEzMjkwMDMsImV4cCI6MTY4MTMzMjYwM30.dRFE3KGOmTmp2b8Gfl8IBXe4Ezqj4Llkm2qDbw_vHmo

### Get user by id
GET {{api}}/d9eef684-4c3f-4448-bd2c-eadacc8159a0

### Create user
POST {{api}}/register
Content-Type: application/json

{
    "firstName": "Kriz",
    "lastName": "Marles",
    "age": 32,
    "email": "kriz.marles@yopmail.com",
    "username": "kriz",
    "password": "admin",
    "country": "Colombia",
    "role": "BASIC"
}

### Update user
PUT {{api}}/edit/d9eef684-4c3f-4448-bd2c-eadacc8159a0
Content-Type: application/json
x_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQkFTSUMiLCJzdWIiOiJmMzMyNTM2NS02ZTk0LTQ2M2EtODJiZi1jNzMxODc3NmJhNzMiLCJpYXQiOjE2NzkzNzE1MTcsImV4cCI6MTY3OTM3NTExN30.G_UhgX86H60pdESA5ear8K6iaTAmtahu1jITjtHNofE


{
    "firstName": "John",
    "lastName": "Doe",
    "age": 34,
    "email": "jhon.doe@yopmail.com",
    "username": "john_doe",
    "password": "admin",
    "country": "Colombia",
    "role": "BASIC"
}

### Link to a project
POST  {{api}}/add-to-project
Content-Type: application/json

{
    "user": "f3325365-6e94-463a-82bf-c7318776ba73",
    "project": "8ecb9752-75c1-4c37-a32d-9775becffa18",
    "accessLevel": 50
}

### Delete user
DELETE  {{api}}/delete/332f023a-0f5d-44fb-954b-9b8ea335d72b